version: '3.8'
services:
  backend:
    container_name: backend
    image: reactapp
    ports:
      - 3000:3000
    command: npx nodemon index.js
    volumes:
      - .:/ReactApp

  frontend:
    container_name: frontend
    image: reactapp
    ports:
      - 83:3000
    command: npm start
    volumes:
      - .:/ReactApp
